### PR TITLE
Deprecate from option for a more explicit value_from

### PR DESCRIPTION
**Pull request by dlinch**
We ran into the `from` option at work, and we had no idea what the hell it meant and had to look it up in the documentation. I thought maybe renaming it would help make it more obvious.

Does this make me an open-source contributor now?

### CODE REVIEW

**Comment by jejacks0n** [comment]
> Does this make me an open-source contributor now?

I think so.. though, this isn't one that'll get you much notoriety.

**Comment by dlinch** [comment]
FYI I tested this against our project and it works, including the warning logging. But I had to do that because there are no tests. 

thisisawkward

**Comment by jejacks0n** [comment]
> Does this make me an open-source contributor now?

I think so.. though, this isn't one that'll get you much notoriety.

**Comment by jejacks0n** [comment]
> FYI I tested this against our project and it works, including the warning logging. But I had to do that because there are no tests.

GOOD NEWS! YOU DON'T NEED TO FIX A BROKEN BUILD! Who needs them tests anyway?

**Comment by jejacks0n** [comment]
Thanks for your work here @dlinch.

**Pull request merged**
